services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
      
  leetcode_api:
    image: alfaarghya/alfa-leetcode-api:2.0.1
    restart: always
    ports:
      - '3001:3000'